import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Montserrat, Open_Sans } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"], // Use 'latin' as it's most commonly used
  weight: ["400", "700"], // Specify the weights you need (regular and bold in this case)
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${openSans.className}`}>
        {children}
      </body>
    </html>
  );
}
